## Sorting Chest
## Super short how-to:
## - give users the sortingchest.sort permission
## - have a user create and place a chest named "source" (by default; see source_chest_name below)
## - within sort_distance blocks, have the user place one or more chests named "destination" (see destination_chest_name below)
## - in those destination chests, the user should add items (incomplete stacks)
## - then, when the user places items into the "source" chest, SorterChest will automatically sort the items into available stack space in the "destination" chest


# Sends debug messages to console
debug: false

# Sends debug messages to the player who triggered the sorter
debug_to_player: false

# the distance away from the Source chest to search for Destination chests (in all axes)
sort_distance: 20

# if this is false, items will only stack up to their normal max stack size
# if true, it will allow any item to stack up to 64
allow_full_stacks: false

# this is the name of the source chest (case-insensitive)
source_chest_name: source

# and the destination chest name (also case-insensitive)
destination_chest_name: destination
