name: SortingChest
main: com.seancoates.minecraft.sortingchest.SortingChestPlugin
version: 0.2.3
commands: {}
permissions:
    sortingchest.sort:
        description: allows users to sort from a sorting chest into a destination chest
